### ISSUE TITLE
MySql max size of data

### ISSUE THREAD

**Issue by radoslavius** [matthiasmullie/scrapbook#10]
Hi,
I'm trying to store data in mysql, but unfortunately I can not store everything (about 250kB) - to db saves only 64kB. What may be the problem? In sqlite it works fine.
Thanks

**Comment by matthiasmullie** [comment]
MySQL's BLOB size is 64kB. I changed it to LONGBLOB in a685f488fb39627987bd0cf49ff096784bd0024e.

To change your existing setup, you can run this query (where $table is your table name):

``` sql
ALTER TABLE $table MODIFY v LONGBLOB;
```
