### ISSUE TITLE
Links to Adapters are broken on scrapbook.cash homepage

### ISSUE THREAD

**Issue by tback** [matthiasmullie/scrapbook#12]
There isn't much more to say:
Links go to `/adapters/<adapter>.html` but they live at `/adapters/<adapter>/` these days.

![wrong link](https://cloud.githubusercontent.com/assets/83432/18121557/6917456e-6f65-11e6-90d6-8fd903be6b4d.png)

**Comment by matthiasmullie** [comment]
Hey @tback, thanks for noticing! I just fixed this with 3b0e8c7
