### ISSUE TITLE
psr/simple-cache dependency

### ISSUE THREAD

**Issue by mindplay-dk** [matthiasmullie/scrapbook#13]
`psr/simple-cache` is now [available](https://packagist.org/packages/psr/simple-cache) on Packagist as `0.1.0` - you can now remove the built-in copy of the interfaces, extra `autoload` config, etc.

If you'd like me to PR this change, let me know? I have some free time tomorrow :-)

**Comment by matthiasmullie** [comment]
I'll get to this soonish, but feel free to send a PR is you have the time :)

**Comment by mindplay-dk** [comment]
OK, will PR this tomorrow :-)
