### ISSUE TITLE
Incompatibility with Memcached 3

### ISSUE THREAD

**Issue by martin-georgiev** [matthiasmullie/scrapbook#22]
I am checking if a non-existing key is set in Memcached. When I use `SimpleCache::has` I get the following error:
> Warning: Memcached::getMulti() expects parameter 2 to be integer, array given in .../matthiasmullie/scrapbook/src/Adapters/Memcached.php on line 72

In Memcached v3 (the only version properly supported for PHP 7) the signature of `getMulti()` changed and now expects 2 arguments instead of the 3 before.
This means that any usage of `getMulti()` with the Memcached adapter will result in error.
This should be handled in a graceful manner, so both v2 and v3 of the Memcached API are supported.
The code causing headaches is on [this line](https://github.com/matthiasmullie/scrapbook/blob/master/src/Adapters/Memcached.php#L70) in `Adapters\Memcached`.

Scrapbook version: 1.4
PHP version: 7.1
Memcached version: 3.0

**Comment by martin-georgiev** [comment]
Two options I'll consider to solve this situation:
- Check the Memcached version and based on that value decide which arguments to pass. This should be the preferable way to do it.
- Use [`ReflectionMethod`](http://php.net/manual/en/class.reflectionmethod.php) to test for the number of expected arguments. This solution is dirty and shouldn't be considered as a long-term solution, as Memcached's API can change again in the future.

**Comment by matthiasmullie** [comment]
Hey @martin-georgiev, thanks for the detailed report!

I just pushed a new commit that should fix this issue - any chance you could try it out (it's in master) before I push a new release?

**Comment by martin-georgiev** [comment]
Thanks @matthiasmullie,
I can confirm that the change is behaving as expected now.

There is a separate, less significant problem. The library will not handle gracefully the case when `\Memcached::getMulti()` [returns `false`](http://php.net/manual/en/memcached.getmulti.php). Such cases will produce an error:
> Warning: Invalid argument supplied for foreach() in .../matthiasmullie/scrapbook/src/Adapters/Memcached.php on line 73

I think this should be handled within the `Adapters\Memcached` (e.g. throwing a descriptive exception).

**Comment by matthiasmullie** [comment]
Thanks for the PR for that last issue! :)
