### ISSUE TITLE
SimpleCache TTL

### ISSUE THREAD

**Issue by bkdotcom** [matthiasmullie/scrapbook#28]
https://github.com/matthiasmullie/scrapbook/blob/master/src/Psr16/SimpleCache.php#L243-L252

```PHP
/*
 * PSR-16 only accepts relative timestamps, whereas KeyValueStore
 * accepts both relative & absolute, depending on what the timestamp
 * is. We'll have to convert all ttls here to absolute, to make sure
 * KeyValueStore doesn't get confused.
 * @see https://github.com/dragoonis/psr-simplecache/issues/3
 */
if ($ttl < 30 * 24 * 60 * 60) {
    return $ttl + time();
}
```

The logic is backwards
If I pass a TTL of 60 days `60 * 24 * 60 * 60`...  the above code will NOT add `time()`...  it will then get passed to `KeyValueStore` unmodified.  `KeyValueStore` will interpret it as an absolute timestamp (1970-03-02 00:00:00)... which is expired

Per the block comment:  "PSR-16 only accepts relative timestamps... We'll have to convert all ttls here to absolute,"...   the code then proceeds to only convert some TTLs.

Since a relative TTL is always passed to SimpleCache, the 30-days condition isn't necessary...   time() should always be added to absolutify  (unless `$ttl === 0`... which is already being checked for)

Should simply be:
```PHP
// if ($ttl < 30 * 24 * 60 * 60) {
    return $ttl + time(); // always convert relative TTL to absolute
// }
```

**Comment by matthiasmullie** [comment]
Absolutely correct, thanks for noticing!
