### ISSUE TITLE
MemoryStore size/limit with collections

### ISSUE THREAD

**Issue by bkdotcom** [matthiasmullie/scrapbook#29]
MemoryStore limit enforcement goes out the window when collections are created

```
$adapter = new MemoryStore(1000);
$collectionFoo = $adapter->getCollection('foo');
$collectionBar = $adapter->getCollection('bar');

// $adapter, $collectionFoo, & $collectionBar all have independent limits of 1000
// we requested a limit of 1000... but we can go 3 times over
```

* Spawned collections get independent limit vs shared limit
* "Parent" adapter doesn't track the size of spawned collections.   Spawned collections are oblivious of parent and each other.
* "Least Recently Used" ignores collections
    * items in child collections should be fair game when evicting
    * items in ancestor collections should _probably_ not be fair game

**Comment by matthiasmullie** [comment]
Nice catch!
I fixed this, though slightly different than what you suggested: if new data is added to collections, it can also lead to evictions in the parent.
That is fair game, IMO: other cache backends will also evict whatever they deem necessary, regardless of whether it's in a parent or child (these collections are mostly artificial anyway, implemented via prefixing - they're not separate cache servers)
En plus: it's not about data persistence (especially not in a "memory store") - it's ok for data to fall out of cache (a cache eviction is just meant to prevent the app from blowing up if one attempts to store too much data)

**Comment by bkdotcom** [comment]
Awesome!

~~`MatthiasMullie\Scrapbook\Adapters\Collections\MemoryStore` also needs to extend `flush()`~~

der... was thinking that flush should also update $size...  but nothing is actually immediately "evicted"...
related to #30
