### ISSUE TITLE
tests cache/integration-tests dependency

### ISSUE THREAD

**Issue by bkdotcom** [matthiasmullie/scrapbook#32]
This may fall under "question", and if so, I apologize...

tests/Docker/build-php.sh 
calls
`composer require league/flysystem`

when/how does 
`composer require --dev cache/integration-tests:dev-master`
get called (via travis)?

`make test`

> There were 2 incomplete tests:
>
> 1) MatthiasMullie\Scrapbook\Tests\Psr6\Integration\IntegrationPoolTest::testIncomplete
Missing dependencies. Please run: composer require --dev cache/integration-tests:dev-master
>
> /var/www/tests/bootstrap.php:42
>
> 2) MatthiasMullie\Scrapbook\Tests\Psr16\Integration\IntegrationTest::testIncomplete
Missing dependencies. Please run: composer require --dev cache/integration-tests:dev-master
>
> /var/www/tests/bootstrap.php:57

**Comment by matthiasmullie** [comment]
It looks like I lost this dependency while switching over to Docker for the tests.
Added cache/integration-tests to build-php.sh as well!
