### ISSUE TITLE
Stampede protection with "stale-while-revalidate" strategy?

### ISSUE THREAD

**Issue by mindplay-dk** [matthiasmullie/scrapbook#40]
I'm fetching data from an external API, and these requests can take 3-5 seconds to complete.

The information I'm getting from this API is secondary content for the page - so it's okay to cache this probably for 5 minutes before pulling updated data from the API.

The stampede protection strategy will take care of the problem of making too many requests to this external API.

Being cached for 5 minutes, it's also not crucial to have the latest information within a 5-minute window, and so I'm looking for a means of implementing a "stale while revalidate" pattern.

That is, I don't want to block the rendering of a page for *any* user while fetching an updated version of the cached content - if the content has expired, I'd like to trigger an update in the background (e.g. via `register_shutdown_handler()`) and just return what we have.

Would it make sense to expand the stampede protection decorator with a feature like that?

Or is it best left to a separate decorator?

Is this feature useful/common enough that you might want it in your library?

**Comment by matthiasmullie** [comment]
My sincere apologies for this absurdly late reply.

Yes, it would make a lot of sense for this feature to be implemented, and I would very much welcome any pull request to implement it.

However, back when originally implementing the current stampede protection implementation, I did consider this approach as well. And there was a reason I didn't end up also implementing this. 

I can't remember the exact reasons, though. Perhaps something about it simply didn't fit the interface, perhaps it had something to do with cross-adapter or PHP/HHVM versions compatibility, perhaps something else entirely. I'm sorry, but I can't remember.

If (so long after you originally submitted this) you still have an interest in pursuing this and think it is feasible to implement, I would be very interested to receive of pull request, or cooperate to help see this through!

**Comment by mindplay-dk** [comment]
I haven't used PHP in years. Feel free to close this. 😅

**Comment by mindplay-dk** [comment]
I hope this didn't come off crass like I was trying to imply something about PHP or your library.

For the record, your library worked great! The company I worked at are still using it and afaik they've always been very happy with that choice. Just that I haven't personally been working with PHP in the last couple of years. ☺

**Comment by matthiasmullie** [comment]
Haha, don't worry about it; no offense taken - I read nothing crass in there, just a factual statement that this particular thing has become irrelevant for you.
(And I mean, why would it even still be relevant almost 4 years later :D)
