### ISSUE TITLE
Transaction savepoint

### ISSUE THREAD

**Issue by PandCar** [matthiasmullie/scrapbook#47]
Add please "transaction savepoint" for the ability to implement nested transactions
Or just implement nested transactions

**Comment by matthiasmullie** [comment]
Alas, this is not possible. Transactions are not a thing actually supported by most clients, and the transactional layer is just playing pretend by cleverly layering, ordering & invalidating cache instructions. Savepoints and nested transactions are simply, and sadly, not possible.
