### ISSUE TITLE
undefined method: collection

### ISSUE THREAD

**Issue by zlo2k** [matthiasmullie/scrapbook#52]
Hi!
I am trying to run a simple example and I get the error:

Fatal error: Uncaught Error: Call to undefined method MatthiasMullie\Scrapbook\Adapters\Memcached::collection() in test.php:8 Stack trace: #0 {main} thrown in test.php on line 8

Apache 2.4, PHP 7.2, Memcached server 1.5, 
PHPINFO Memcached section:
Version | 3.1.4
libmemcached version | 1.0.18

```
<?php
require_once 'vendor/autoload.php';

$client = new \Memcached();
$client->addServer('localhost', 11211);
$cache = new \MatthiasMullie\Scrapbook\Adapters\Memcached($client);

$articleCache = $cache->collection('articles');
$sessionCache = $cache->collection('sessions');

$cache->set('key', 'value one');
$articleCache->set('key', 'value two');
$sessionCache->set('key', 'value three');

$articleCache->flush();

$cache->flush();
```

Maybe I was wrong about something?

**Comment by matthiasmullie** [comment]
The method to call is `->getCollection()` rather than `->collection()`.
